<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Συμπέρασμα',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Συγχαρητήρια! Η παραμετροποίηση του διακομιστή σας ικανοποιεί όλες τις απαιτήσεις του Yii.',
  'Description' => 'Περιγραφή',
  'Details' => 'Λεπτομέρειες',
  'Failed' => 'Απέτυχε',
  'Memo' => 'Σημειώσεις',
  'Name' => 'Όνομα',
  'Passed' => 'Πέρασε',
  'Required By' => 'Απαιτούμενο από',
  'Result' => 'Αποτέλεσμα',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Αυτή η σελίδα ελέγχει αν η παραμετροποίηση του διακομιστή σας είναι σωστή για την εκτέλεση των εφαρμογών ιστού του <a href="http://www.yiiframework.com/">Yii</a>. Ελέγχει αν ο διακομιστής εκτελεί τη σωστή έκδοση PHP, αν έχουν φορτωθεί οι κατάλληλες επεκτάσεις PHP και αν οι ρυθμίσεις του αρχείου php.ini είναι σωστές.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'Δυστυχώς, η παραμετροποίηση του διακομιστή σας δεν ικανοποιεί τις απαιτήσεις του Yii.',
  'Warning' => 'Προειδοποίηση',
  'Yii Requirement Checker' => 'Ελεγκτής Απαιτήσεων Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'Η παραμετροποίηση του διακομιστή σας ικανοποιεί τις ελάχιστες απαιτήσεις του Yii. Παρακαλούμε δείτε με προσοχή τις παρακάτω προειδοποιήσεις εφόσον η εφαρμογή σας θα χρησιμοποιεί τα αντίστοιχα χαρακτηριστικά.',
);
