<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Rozstrzygnięcie',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Gratulacje! Konfiguracja Twojego serwera spełnia wszystkie wymagania stawiane przez Yii.',
  'Description' => 'Opis',
  'Details' => 'Szczegóły',
  'Failed' => 'Nie powiódł się',
  'Memo' => 'Notka',
  'Name' => 'Nazwa',
  'Passed' => 'Powiódł się',
  'Required By' => 'Wymagana przez',
  'Result' => 'Rezultat',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Skrypt ten sprawdza czy konfiguracja Twojego serwera spełnia wymagania pozwalające uruchomić aplikację napisaną przy użyciu <a href="http://www.yiiframework.com/">Yii</a>. Sprawdza on, czy serwer używa poprawnej wersji PHP, czy zostały załadowane odpowiednie rozszerzenia PHP oraz czy ustawienia w pliku php.ini są prawidłowe.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'Niestety konfiguracja Twojego serwera nie spełnia wymagań stawianych przez Yii.',
  'Warning' => 'Ostrzeżenie',
  'Yii Requirement Checker' => 'Sprawdzanie wymagań przez Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'Konfiguracja Twojego serwera spełnia minimalne wymagania stawiane przez Yii. Zwróć uwagę na ostrzeżenia wyświetlone poniżej jeśli Twoja aplikacja będzie używała odpowiadających im funkcjonalności.',
);
