<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Conclusion',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Félicitations ! Votre configuration vérifie toutes les exigences de Yii.',
  'Description' => 'Description',
  'Details' => 'Details',
  'Failed' => 'Echec',
  'Memo' => 'Info',
  'Name' => 'Nom',
  'Passed' => 'Ok',
  'Required By' => 'Requis Par',
  'Result' => 'Resultat',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Ce script vérifie si la configuration de votre serveur satisfait toutes les dépendances nécessaires pour exécuter les applications <a href="http://www.yiiframework.com/">Yii</a>. Il vérifie si le serveur exécute la version correcte de PHP, si toutes les extensions PHP nécessaires ont été chargées, et si les paramètres du fichier php.ini sont corrects.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'Malheureusement, votre configuration ne satisfait pas les exigences de Yii.',
  'Warning' => 'Avertissement',
  'Yii Requirement Checker' => 'Vérification de la configuration nécessaire pour Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'Votre configuration satisfait les exigences minimales de Yii. Notez les avertissements listés ci-dessous si votre application utilise les fonctionnalités correspondantes.',
);
