<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER ne contient pas {vars}.',
  '$_SERVER variable' => 'variable $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] doit être égal au chemin du script d\'entrée.',
  'APC extension' => 'extension APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Toutes les <a href="http://www.yiiframework.com/doc/api/#system.db">classes relatives aux BD</a>.',
  'Ctype extension' => '',
  'DOM extension' => 'extension DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Soit $_SERVER["REQUEST_URI"] soit $_SERVER["QUERY_STRING"] doit être défini.',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => '',
  'GD installed,<br />FreeType support not installed' => '',
  'GD or ImageMagick not installed' => '',
  'Mcrypt extension' => 'extension Mcrypt',
  'Memcache extension' => 'extension Memcache',
  'PCRE extension' => 'extension PCRE',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => '',
  'PDO MSSQL extension (pdo_dblib)' => '',
  'PDO MSSQL extension (pdo_mssql)' => '',
  'PDO MySQL extension' => 'extension PDO MySQL',
  'PDO Oracle extension' => '',
  'PDO PostgreSQL extension' => 'extension PDO PostgreSQL',
  'PDO SQLite extension' => 'extension PDO SQLite',
  'PDO extension' => 'extension PDO',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 ou supérieur est requis.',
  'PHP version' => 'Version de PHP',
  'Reflection extension' => 'extension Reflection',
  'SOAP extension' => 'extension SOAP',
  'SPL extension' => 'extension SPL',
  'The system is unable to find the requested action "{action}".' => '',
  'This is required by encrypt and decrypt methods.' => 'Nécessaire pour les méthodes encrypt et decrypt.',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => '',
  'This is required if you are using MSSQL database from MS Windows' => '',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => '',
  'This is required if you are using MySQL database.' => 'Cette extension est requise si vous utilisez une base de donnée MySQL.',
  'This is required if you are using Oracle database.' => '',
  'This is required if you are using PostgreSQL database.' => 'Cette extension est requise si vous utilisez une base de donnée PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Cette extension est requise si vous utilisez une base de donnée SQLite.',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Impossible de déterminer les informations sur le chemin dans l\'URL. Vérifier que $_SERVER["PATH_INFO"] (ou $_SERVER["PHP_SELF"] et $_SERVER["SCRIPT_NAME"]) ont la bonne valeur',
);
