<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Approved' => 'Опубликован',
  'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить?',
  'Change User' => 'Изменил',
  'Comment Text' => 'Текст комментария',
  'Comments' => 'Комментарии',
  'Create' => 'Создать',
  'Create Time' => 'Время публикации',
  'Delete' => 'Удалить',
  'Deleted' => 'Удален',
  'Edit' => 'Изменить',
  'Manage' => 'Управление',
  'Model' => 'Модель',
  'Name' => 'Имя',
  'Not approved' => 'Не опубликован',
  'Post author' => 'Автор публикации',
  'Post Comment' => 'Оставить комментарий',
  'Remove' => 'Удалить',
  'Save' => 'Сохранить',
  'Search' => 'Поиск',
  'Sorry, you have to login to leave a comment.' => 'Войдите, чтобы оставить комментарий',
  'Spam' => 'Спам',
  'Status' => 'Статус',
  'Submit' => 'Отправить',
  'Unknown status' => 'Неизвестный статус',
  'Update' => 'Сохранить',
  'Update Time' => 'Обновлено',
  'User' => 'Автор',
  'Verify Code' => 'Проверочный код',
  'View' => 'Смотреть',
  '{n} Comment|{n} Comments' => '{n} Комментарий|{n} Комментария|{n} Комментариев',
);
