<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Заключение',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Поздравление! Вашият сървър отговаря на всики изисквания за работа на Yii.',
  'Description' => 'Описание',
  'Details' => 'Детайли',
  'Failed' => 'Провален',
  'Memo' => 'Бележка',
  'Name' => 'Име',
  'Passed' => 'Преминат',
  'Required By' => 'Поискано от',
  'Result' => 'Резултат',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Този скрипт проверява дали конфигурацията на вавият сървър, отговаря на изискванията за работа на <a href="http://www.yiiframework.com/">Yii</a> уеб приложенията. Проверява дали на сървъра работи подходящата версия на PHP, дали подходящите PHP добавки са заредени и дали настройките в php.ini са вярни.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'За жалост, вашият сървър, не отговаря на изискванията за работа на Yii.',
  'Warning' => 'Предупреждение',
  'Yii Requirement Checker' => 'Проверка на изискванията на Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'Вашият сървър удоблетворява минималните изисквания на Yii. Моля, обърнете внимание на списъка с грешки отдоло, ако вашето приложение ще използва тези функции.',
);
