<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER няма {vars}.',
  '$_SERVER variable' => '$_SERVER променлива',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] трябва да бъде същия като пътя до началния скрипт',
  'APC extension' => 'APC добавка',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Всички <a href="http://www.yiiframework.com/doc/api/#system.db">класове за работа с базата от данни</a>.',
  'Ctype extension' => '',
  'DOM extension' => 'DOM разширение',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Или $_SERVER["REQUEST_URI"] или $_SERVER["QUERY_STRING"] трябва да съществуват',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => '',
  'GD installed,<br />FreeType support not installed' => '',
  'GD or ImageMagick not installed' => '',
  'Mcrypt extension' => 'Mcrypt разширение',
  'Memcache extension' => 'Memcache разширение',
  'PCRE extension' => 'PCRE разширение',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => '',
  'PDO MSSQL extension (pdo_dblib)' => '',
  'PDO MSSQL extension (pdo_mssql)' => '',
  'PDO MySQL extension' => 'PDO MySQL разширение',
  'PDO Oracle extension' => '',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL разширение',
  'PDO SQLite extension' => 'PDO SQLite разширение',
  'PDO extension' => 'PDO разширение',
  'PHP 5.1.0 or higher is required.' => 'Изисква се минимум PHP 5.1.0.',
  'PHP version' => 'PHP версия',
  'Reflection extension' => 'Reflection разширение',
  'SOAP extension' => 'SOAP разширение',
  'SPL extension' => 'SPL разширение',
  'This is required by encrypt and decrypt methods.' => 'Тове се изисква от методите за криптиране/декриптиране.',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => '',
  'This is required if you are using MSSQL database from MS Windows' => '',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => '',
  'This is required if you are using MySQL database.' => 'Това се изисква ако използвате MySQL база от данни.',
  'This is required if you are using Oracle database.' => '',
  'This is required if you are using PostgreSQL database.' => 'Това се изисква ако използвате PostgreSQL база от данни.',
  'This is required if you are using SQLite database.' => 'Това се изисква ако използвате SQLite база от данни.',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Невъзможно е да се определи URL адреса. Моля, проверете дали $_SERVER["PATH_INFO"] (или $_SERVER["PHP_SELF"] и $_SERVER["SCRIPT_NAME"]) съдържат коректни стойности.',
);
