<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Conclusioni',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Congratulazioni! La configurazione del tuo server soddisfa tutti i requisiti di Yii.',
  'Description' => 'Descrizione',
  'Details' => 'Dettagli',
  'Failed' => 'Fallito',
  'Memo' => 'Memo',
  'Name' => 'Nome',
  'Passed' => 'Superato',
  'Required By' => 'Richiesto da',
  'Result' => 'Resultato',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Questo script verifica se la configurazione del tuo server soddisfa i requisiti di esecuzione delle web application sviluppate con <a href="http://www.yiiframework.com/">Yii</a>. Verifica se nel server è in esecuzione la corretta versione di PHP, se le estensioni PHP necessarie sono state caricate e se le impostazioni di php.ini sono corrette.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'Sfortunatamente La configurazione del tuo server non soddisfa i requisiti di Yii.',
  'Warning' => 'Avviso',
  'Yii Requirement Checker' => 'Verifica soddisfazione requisiti di Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'La configurazione del tuo server soddisfa i requisiti minimi di Yii. Si prega di prestare attenzione agli avvisi qui sotto qualora l\'applicazione utilizzi le corrispondenti funzionalità.',
);
