<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => '',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => '',
  'Description' => '',
  'Details' => '',
  'Failed' => '',
  'Memo' => '',
  'Name' => '',
  'Passed' => '',
  'Required By' => '',
  'Result' => '',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => '',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => '',
  'Warning' => '',
  'Yii Requirement Checker' => '',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => '',
);
