<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER inneholder ikke {vars}',
  '$_SERVER variable' => '$_SERVER variabel',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] må være lik filbanen til startscriptet',
  'APC extension' => 'APC-tillegg',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Alle <a href="http://www.yiiframework.com/doc/api/#system.db">DB-relaterte klasser</a>',
  'Ctype extension' => '',
  'DOM extension' => 'DOM-extension',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => '',
  'GD installed,<br />FreeType support not installed' => '',
  'GD or ImageMagick not installed' => '',
  'Mcrypt extension' => 'Mcrypt-extension',
  'Memcache extension' => 'Memcache-extension',
  'PCRE extension' => 'PCRE-extension',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => '',
  'PDO MSSQL extension (pdo_dblib)' => '',
  'PDO MSSQL extension (pdo_mssql)' => '',
  'PDO MySQL extension' => 'PDO MYSQL-extension',
  'PDO Oracle extension' => '',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL-extension',
  'PDO SQLite extension' => 'PDO SQLite-extension',
  'PDO extension' => 'PDO-extension',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 eller nyere er påkrevet',
  'PHP version' => 'PHP-versjon',
  'Reflection extension' => 'Reflection-extension',
  'SOAP extension' => 'SOAP-extension',
  'SPL extension' => 'SPL-extension',
  'This is required by encrypt and decrypt methods.' => 'Dette kreves av kryptering- og dekrypteringsmetodene.',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => '',
  'This is required if you are using MSSQL database from MS Windows' => '',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => '',
  'This is required if you are using MySQL database.' => 'Dette kreves hvis du bruker en MySQL database.',
  'This is required if you are using Oracle database.' => '',
  'This is required if you are using PostgreSQL database.' => 'Dette kreves hvis du bruker en PostgreSQL database.',
  'This is required if you are using SQLite database.' => 'Dette kreves hvis du bruker en SQLite database.',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Kunne ikke finne path info. Vennligst sjekk at $_SERVER["PATH_INFO"] (eller $_SERVER["PHP_SELF"] og $_SERVER["SCRIPT_NAME"]) inneholder riktige verdier.',
);
