<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Záver',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Gratulujem! Váš server spĺňa všetky požiadavky potrebné pre korektné fungovanie Yii.',
  'Description' => 'Popis',
  'Details' => 'Detaily',
  'Failed' => 'Chyba',
  'Memo' => 'Pozn.',
  'Name' => 'Názov',
  'Passed' => 'OK',
  'Required By' => 'Požadované od',
  'Result' => 'Výsledok',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Tento skript preverí, či je konfigurácia vášho servera postačujúca pre korektné fungovanie aplikácii vytvorených pre <a href="http://www.yiiframework.com/">Yii framework</a>. Test preveruje správnu verziu PHP, prítomnosť potrebných PHP rozšírení a správne nastavenie konfigurácie v php.ini.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'Bohužiaľ, váš server nespĺňa požiadavky potrebné pre fungovanie Yii.',
  'Warning' => 'Upozornenie',
  'Yii Requirement Checker' => 'Yii - Test prostredia',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'Váš server spĺňa minimálne požiadavky potrebné pre fungovanie Yii.Venujte prosím pozornosť upozorneniam uvedeným nižšie v prípade, že vaša aplikácia bude využívať potrebné funkcie.',
);
