<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Alert text after send message from full form' => 'Текст сообщения после отправки полной версии формы',
  'City' => 'Город',
  'Contact form and mail settings' => 'Форма обратной связи и настройки отправки',
  'Contacts' => 'Контакты',
  'Enable send mail via SMTP?' => 'Включить отправку почты через SMTP?',
  'Enter Code' => 'Введите код',
  'For example disable on McHost.ru. Option worked only throw PHP mail(), not SMTP' => 'На примере хостинга McHost.ru рекоммендуется отключить. Опция действует ТОЛЬКО при отправке через PHP mail(), не SMTP',
  'Full form class name' => 'Имя класса полной версии формы',
  'Message Text' => 'Текст сообщения',
  'Message from {site}' => 'Письмо с сайта {site}',
  'Message title' => 'Тема письма',
  'Message title of full form' => 'Заголовок сообщения полной версии формы',
  'Module for sending messages from site' => 'Модуль для отправки сообщений с сайта',
  'Only for simple form. Anti-spam.' => 'Только для простой формы. Используется для бобрьбы против спаммеров',
  'Problem with sending message. Write to administrator:' => 'Произошла проблема с отправкой письма! Обратитесь к администратоу:',
  'Required Captcha?' => 'Требовать ввод кода с картинки',
  'SMTP Server Host' => 'SMTP Адрес сервера',
  'SMTP login' => 'SMTP логин',
  'SMTP password' => 'SMTP пароль',
  'SMTP port' => 'SMTP порт',
  'SMTP type connection' => 'SMTP тип соединения',
  'Send' => 'Отправить',
  'Set from email address' => 'Указывать адрес отправителя',
  'Thanks for message!' => 'Спасибо за сообщение! Мы Вам обязательно ответим!',
  'You name?' => '',
  'Не меняйте, если не уверены' => '',
  'Опросный лист с сайта' => '',
);
