<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER verfügt nicht über {vars}.',
  '$_SERVER variable' => '$_SERVER Variable',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] muss der selbe Eingangsscriptpfad sein.',
  'APC extension' => 'APC Erweiterung',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Alle <a href="http://www.yiiframework.com/doc/api/#system.db">DB-bezüglichen Klassen</a>',
  'Ctype extension' => '',
  'DOM extension' => 'DOM Erweiterung',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Entweder $_SERVER["REQUEST_URI"] oder $_SERVER["QUERY_STRING"] müssen exisitieren.',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => '',
  'GD installed,<br />FreeType support not installed' => '',
  'GD or ImageMagick not installed' => '',
  'Mcrypt extension' => 'Mcyrpt Erweiterung',
  'Memcache extension' => 'Memcache Erweiterung',
  'PCRE extension' => 'PCRE Erweiterung',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => '',
  'PDO MSSQL extension (pdo_dblib)' => '',
  'PDO MSSQL extension (pdo_mssql)' => '',
  'PDO MySQL extension' => 'PDO MySQL Erweiterung',
  'PDO Oracle extension' => '',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL Erweiterung',
  'PDO SQLite extension' => 'PDO SQLite Erweiterung',
  'PDO extension' => 'PDO Erweiterung',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 oder Neuer wird benötigt.',
  'PHP version' => 'PHP Version',
  'Reflection extension' => 'Reflection Erweiterung',
  'SOAP extension' => 'SOAP Erweiterung',
  'SPL extension' => 'SPL Erweiterung',
  'This is required by encrypt and decrypt methods.' => '',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => '',
  'This is required if you are using MSSQL database from MS Windows' => '',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => '',
  'This is required if you are using MySQL database.' => 'Dies wird bei Verwendung einer MySQL Datenbank benötigt.',
  'This is required if you are using Oracle database.' => '',
  'This is required if you are using PostgreSQL database.' => 'Dies wird bei Verwendung einer PostgreSQL Datenbank benötigt.',
  'This is required if you are using SQLite database.' => 'Dies wird bei Verwendung einer SQLite Datenbank benötigt.',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Die URL Pfadinformation kann nicht ermittelt werden. Stellen Sie bitte sicher, dass entweder $_SERVER["PATH_INFO"] (oder $_SERVER["PHP_SELF"] und $_SERVER["SCRIPT_NAME"]) mit korrekten Werten gefüllt sind.',
);
