<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Conclusión',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Felicitaciones! Su servidor satisface todos los requerimientos de Yii.',
  'Description' => 'Descripción',
  'Details' => 'Detalles',
  'Failed' => 'Fallo',
  'Memo' => 'Memo',
  'Name' => 'Nombre',
  'Passed' => 'Paso',
  'Required By' => 'Requerido por',
  'Result' => 'Resultado',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Este script verifica que la configuración de su servidor cumpla con los requerimientos para poder ejecutar aplicaciones Web <a href="http://www.yiiframework.com/">Yii</a>. El mismo verifica que el servidor este corriendo una versión adecuada de PHP, que las extensiones PHP necesarias hayan sido cargadas y que las configuraciones del archivo php.ini sean correctas.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'Desafortunadamente la configuración de su servidor no satisface los requerimientos de Yii.',
  'Warning' => 'Advertencia',
  'Yii Requirement Checker' => 'Verificación de requerimientos de Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'La configuración de su servidor satisface los requerimientos mínimos de Yii. Por favor preste atención a las advertencias listadas en el cuadro más abajo si su aplicación utiliza alguna de esas características.',
);
