<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<i class="icon-search"></i> Search <span class="caret"></span>' => '<i class="icon-search"></i> Поиск <span class="caret"></span>',
  'Add' => 'Добавить',
  'Add photo…' => 'Добавить фото…',
  'Adding' => 'Добавление',
  'Album' => 'Альбом',
  'Albums' => 'Альбомы',
  'Author' => 'Автор',
  'Change selected' => 'Изменить выбранные',
  'Changing' => 'Изменение',
  'Close' => 'Закрыть',
  'Create and manage albums with photos' => 'Создание и управление альбомами с фотографиями',
  'Created' => 'Создано',
  'Description' => 'Описание',
  'Directory for photos' => 'Папка галереи для фотографий',
  'Edit Data' => 'Изменить данные',
  'Fields with <span class="required">*</span> is required.' => 'Поля, отмеченные <span class="required">*</span> обязательны для заполнения.',
  'File' => 'Файл',
  'Gallery' => 'Галерея',
  'Hidden' => 'Скрыто',
  'Hidden. Publish?' => 'Скрыто. Опубликовать?',
  'Keywords' => 'Ключевые слова',
  'Manage' => 'Управление',
  'Max photo height after upload' => 'Максимальная высота фото после загрузки',
  'Max photo width after upload' => 'Максимальная ширина фото после загрузки',
  'Max thumb photo width after upload' => 'Максимальная ширина миниатюры фото',
  'Name' => 'Название',
  'Order' => 'Порядок',
  'Photos' => 'Фотографии',
  'Published' => 'Опубликовано',
  'Published. Hide?' => 'Опубликовано. Скрыть?',
  'Remove selected' => 'Удалить выбранные',
  'Save' => 'Сохранить',
  'Search' => 'Искать',
  'Select All' => 'Выбрать все',
  'Slug' => 'Ссылка',
  'Status' => 'Статус',
  'Supported photo formats' => 'Форматы фотографий',
  'Title' => 'Заголовок (title)',
  'Type' => 'Тип',
  'Update User' => 'Изменил',
  'If you use Gallery with Folio theme (default), change CSS:
					<br/> .galleria-thumbnails .galleria-image {width: 130px}
					<br/>File: ./extensions/galleria/assets/themes/folio/galleria.folio.css
					<br/>else thumbnail will be show in 130px width' => 'Если используется галерея Gallery с темой Folio (по умолчанию), нужно изменить значение параметра в CSS:
					<br/> .galleria-thumbnails .galleria-image {width: 130px}
					<br/>Файл: ./extensions/galleria/assets/themes/folio/galleria.folio.css
					<br/>иначе превью будут показываться размером по умолчанию 130px в ширину',
);
