<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Concluzie',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Felicitari! Configuratia serverului dvs indeplineste toate cerintele Yii.',
  'Description' => 'Descriere',
  'Details' => 'Detalii',
  'Failed' => 'Failed',
  'Memo' => 'Precizari',
  'Name' => 'Nume',
  'Passed' => 'Passed',
  'Required By' => 'Cerut de',
  'Result' => 'Rezultat',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Acest script verifica daca configuratia serverului dvs indeplineste cerintele pentru rularea aplicatiilor Web <a href="http://www.yiiframework.com/">Yii</a>. Se fac urmatoarele verificari: daca serverul ruleaza versiunea corecta de PHP, daca extensiile PHP corespunzatoare au fost incarcate si daca setarile din fisierul php.ini sunt corecte.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'Din pacate, configuratia serverului dvs nu indeplineste cerintele Yii.',
  'Warning' => 'Warning',
  'Yii Requirement Checker' => 'Verificarea cerintelor Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'Configuratia serverului dvs indeplineste cerintele minime pentru Yii. Va rugam sa cititi avertismentele afisate mai jos, in cazul in care aplicatia pe care o veti creava folosi respectivele feature-uri.',
);
