<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER nu are {vars}.',
  '$_SERVER variable' => 'Variabila $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] trebuie sa fie aceeasi cu calea fisierului scriptului de intrare.',
  'APC extension' => 'Extensia APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Toate <a href="http://www.yiiframework.com/doc/api/#system.db">clasele de legatura cu bazele de date</a>',
  'Ctype extension' => '',
  'DOM extension' => 'Extensia DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Trebuie sa existe fie $_SERVER["REQUEST_URI"] fie $_SERVER["QUERY_STRING"].',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => '',
  'GD installed,<br />FreeType support not installed' => '',
  'GD or ImageMagick not installed' => '',
  'Mcrypt extension' => 'Extensia Mcrypt',
  'Memcache extension' => 'Extensia  Memcache',
  'PCRE extension' => 'Extensia PCRE',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => '',
  'PDO MSSQL extension (pdo_dblib)' => '',
  'PDO MSSQL extension (pdo_mssql)' => '',
  'PDO MySQL extension' => 'Extensia PDO MySQL',
  'PDO Oracle extension' => '',
  'PDO PostgreSQL extension' => 'Extensia PDO PostgreSQL',
  'PDO SQLite extension' => 'Extensia PDO SQLite',
  'PDO extension' => 'Extensia PDO',
  'PHP 5.1.0 or higher is required.' => 'Este obligatoriu PHP 5.1.0 sau mai nou.',
  'PHP version' => 'Versiunea PHP',
  'Reflection extension' => 'Extensia Reflection',
  'SOAP extension' => 'Extensia SOAP',
  'SPL extension' => 'Extensia SPL',
  'The system is unable to find the requested action "{action}".' => '',
  'This is required by encrypt and decrypt methods.' => 'Obligatoriu pentru metodele encrypt si decrypt.',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => '',
  'This is required if you are using MSSQL database from MS Windows' => '',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => '',
  'This is required if you are using MySQL database.' => 'Obligatoriu daca folositi baza de date MySQL.',
  'This is required if you are using Oracle database.' => '',
  'This is required if you are using PostgreSQL database.' => 'Obligatoriu daca folositi baza de date PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Obligatoriu daca folositi baza de date SQLite.',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Nu se pot determina informatiile despre calea URL. Asigurati-va ca $_SERVER["PATH_INFO"] (sau $_SERVER["PHP_SELF"] si $_SERVER["SCRIPT_NAME"]) contine valoarea potrivita.',
);
