<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '(not) or' => '(не равно) или',
  '- no parent page -' => '- нет родительской страницы -',
  '<i class="icon-search"></i> Search Pages <span class="caret"></span>' => '<i class="icon-search"></i> Поиск страниц <span class="caret"></span>',
  'Add' => 'Добавить',
  'Adding' => 'Добавление',
  'Adding Page' => 'Добавление страницы',
  'Additional' => 'Дополнительно',
  'All' => 'Все',
  'Annotation to a page' => 'Аннотация к странице',
  'Articles — shows a list of subpages' => 'Статьи — вывод списка вложенных страниц',
  'Author' => 'Создал',
  'Catalog module' => 'Каталог-модуль',
  'Continue reading' => 'Читать полностью',
  'Count Results Per Page' => 'Количество результатов на одну страницу',
  'Created' => 'Создано',
  'Draft' => 'Черновики',
  'Editing Page' => 'Изменение страницы',
  'General' => 'Основное',
  'Link' => 'Ссылка',
  'List Pages' => 'Список страниц',
  'META Description' => 'META описание',
  'META Keywords' => 'META ключевые слова',
  'Main Page (slug)' => 'Главная страница (ссылка)',
  'Manage' => 'Управление',
  'Manage Pages' => 'Управление страницами',
  'Manage Site Pages' => 'Управление страницами сайта',
  'Name in Menu' => 'Название в меню',
  'On Moderation' => 'На модерации',
  'Only for registered users' => 'Доступ только для авторизованных пользователей',
  'Only small image (thumbnail)' => 'Только маленькое фото (превью)',
  'Open on Site' => 'Открыть на сайте',
  'Page Added!' => 'Страница добавлена!',
  'Page Not Found or Deleted!' => 'Страница не найдена или удалена!',
  'Pages' => 'Страницы',
  'Parent' => 'Родитель',
  'Parent Level' => 'Уровень вложенности',
  'Picture' => 'Изображение',
  'Preview' => 'Предпросмотр',
  'Published' => 'Опубликовано',
  'Save' => 'Сохранить',
  'Search' => 'Поиск',
  'See on Site' => 'Просмотреть на сайте',
  'Settings' => 'Настройки',
  'Show thumbnail' => 'Смотреть превью',
  'Sorting' => 'Порядок',
  'Status' => 'Статус',
  'Text' => 'Текст',
  'Title' => 'Заголовок (title)',
  'Type' => 'Тип',
  'Update user' => 'Изменил',
  'Updated' => 'Изменено',
  'Use HTML Editor' => 'Использовать HTML редактор',
  'Use Symbols' => 'Используйте символы',
  'Viewing Page' => 'Просмотр страницы',
  'Через запятую' => '',
  'в начале строки поиска' => '',
  'меньше или равно)' => '',
);
