<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Access Type' => 'Доступ',
  'Active' => 'Активен',
  'Administrator' => 'Администратор',
  'All' => 'Все',
  'All posts' => 'Все публикации',
  'Are you sure you want to delete this item?' => 'Уверены, что хотите удалить?',
  'Author' => 'Автор',
  'Blocked' => 'Заблокирован',
  'Blog' => 'Блог',
  'Blog "{blog}" not found!' => 'Блог "{blog}" не найден!',
  'Blog added!' => 'Блог добавлен!',
  'Blog deleted!' => 'Блог удален!',
  'Blog updated!' => 'Блог обновлен!',
  'Blogs' => 'Блоги',
  'Changed' => 'Изменено',
  'Comment Status' => 'Комменатарии',
  'Comment|Comments|Comments' => 'Комментарий|Комментария|Комментариев',
  'Content' => 'Контент',
  'Create' => 'Создать',
  'Create Post' => 'Создать пост',
  'Create Time' => 'Создано',
  'Delete' => 'Удалить',
  'Deleted' => 'Удален',
  'Description' => 'Описание',
  'Draft' => 'Черновик',
  'ID' => '',
  'Keywords' => 'Ключевые слова',
  'Link' => 'Ссылка',
  'Manage' => 'Управление',
  'Manage Posts' => 'Публикации',
  'Manage Users' => 'Участники',
  'Manage blogs, posts and members' => 'Управление блогами, публикациями и участниками',
  'Member' => 'Участник',
  'Members' => 'Участники',
  'Moderator' => 'Модератор',
  'No' => 'Нет',
  'Note' => 'Заметка',
  'On moderation' => 'На модерации',
  'Post not found!' => 'Страница не найдена!',
  'Posts' => 'Публикация',
  'Private' => 'Приватный',
  'Public' => 'Публичный',
  'Publish Time' => 'Время публикации',
  'Published' => 'Опубликовано',
  'Read more →' => 'Читать дальше →',
  'Role' => 'Роль',
  'Save' => 'Сохранить',
  'Scheduled' => 'Расписание',
  'Search' => 'Поиск',
  'Status' => 'Статус',
  'String contains illegal characters. Allowed: {attribute}' => 'Стркоа содержит запрещенные символы. Разрешены: {attribute}',
  'Tagged' => 'С тэгом',
  'Tags' => 'Тэги',
  'Title' => 'Заголовок',
  'Type' => 'Тип',
  'URL' => 'Ссылка',
  'Update' => 'Обновить',
  'Update Time' => 'Обновлено',
  'User' => 'Пользователь',
  'User already in blog!' => 'Пользователь уже участник блога',
  'View' => 'Смотреть',
  'Yes' => 'Да',
  'member|members' => 'участник|участников',
  'post|posts' => 'публикация|публикаций',
  'private' => 'приватный',
  'public' => 'публичный',
  'select blog' => 'выберите блог',
  'unknown' => 'неизвестно',
);
