<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => '檢查結果',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => '恭喜! 您的伺服器組態設定完全符合Yii的要求.',
  'Description' => '檢查內容說明',
  'Details' => '詳細結果',
  'Failed' => '未通過',
  'Memo' => '備註',
  'Name' => '項目名稱',
  'Passed' => '通過',
  'Required By' => '使用者',
  'Result' => '結果',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => '本網頁用於確認您的伺服器組態設定是否能滿足執行<a href="http://www.yiiframework.com/">Yii</a> Web應用程式的要求. 它將檢查伺服器是否使用正確的PHP版本, 是否安裝了合適的PHP extension, 以及確認php.ini檔案是否正確設定.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => '您的伺服器組態設定未能滿足Yii的要求.',
  'Warning' => '警告',
  'Yii Requirement Checker' => 'Yii系統需求檢查',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => '您的伺服器組態設定符合Yii的最低要求. 請注意下列警告(如果您的應用程式會需要使用到相關功能).',
);
