<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Correct working is guaranteed only with the use of the database <strong>MySQL</strong>. Working with other databases is not tested!' => 'Корректная работа гарантируется только при использовании базы данных <strong>MySQL</strong> Работа с другими БД не тестировалась!',
  'Create Database connection' => 'Создание подключения к базе данных',
  'Database host' => 'Хост БД',
  'Database name' => 'Имя БД',
  'Database password' => 'Пароль БД',
  'Database type' => 'Тип БД',
  'Database username' => 'Логин БД',
  'Table tablePrefix' => 'Префикс таблиц',
);
