<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Заключение',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Поздравляем! Конфигурация Вашего веб-сервера полностью удовлетворяет требованиям Yii.',
  'Description' => 'Описание',
  'Details' => 'Результаты проверки',
  'Failed' => 'Нет',
  'Memo' => 'Пояснение',
  'Name' => 'Название',
  'Passed' => 'Да',
  'Required By' => 'Требуется для',
  'Result' => 'Итог',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Данный скрипт проверяет соответствие конфигурации Вашего веб-сервера требованиям, предъявляемым веб-приложениями <a href="http://www.yiiframework.com/">Yii</a>. В частности, проверяются версия РНР и загруженные расширения РНР, а также корректность настроек файла php.ini.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'К сожалению, конфигурация Вашего веб-сервера не удовлетворяет требованиям Yii.',
  'Warning' => 'Предупреждение',
  'Yii Requirement Checker' => 'Проверка на соответствие требованиям Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'Конфигурация Вашего веб-сервера удовлетворяет минимально необходимым требованиям Yii. Обратите внимание на предупреждения в таблице ниже, если предполагается использование соответствующего функционала.',
);
