<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'An error occurred while installing Rights.' => 'Произошла ошибка при установке модуля Rights.',
	'Application authorization manager must extend the RDbAuthManager class.' => 'Диспетчер разрешений приложения должен быт ьунаследован от класса RDbAuthManager.',
	'Application web user must extend the RWebUser class.' => 'Веб пользователь должен быть унаследован от RWebUser.',
	'Congratulations!' => 'Поздравляем!',
	'Error' => 'Ошибка',
	'Install Rights' => 'Установка модуля Rights',
	'No' => 'Нет',
	'Notice: All your existing data will be lost.' => 'Примечание: Все ваши данные будут потеряны.',
	'Please confirm if you wish to reinstall.' => 'Пожалуйста, подтвердите, если вы хотите, чтобы переустановить.',
	'Please try again or consult the documentation.' => 'Пожалуйста, повторите попытку или обратитесь к документации.',
	'Rights has been installed succesfully.' => 'Модуль Rights был установлен ​​успешно.',
	'Rights is already installed!' => 'Rights уже установлен!',
	'Yes' => 'Да',
	'You can start by generating your authorization items' => 'Вы можете начать с создания разрешений',
	'You must be logged in to install Rights.' => 'Вы должны войти для установки Rights.',
	'here' => 'здесь',
);