<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '- anything -' => '- любой -',
  '<i class="icon-search"></i> Search <span class="caret"></span>' => '<i class="icon-search"></i> Поиск <span class="caret"></span>',
  'META Keywords' => 'META ключевые слова',
  'META Description' => 'META описание',
  'Author' => 'Автор',
  'News announce (short)' => 'Анонс новости',
  'All' => 'Все',
  'Date' => 'Дата',
  'Add' => 'Добавить',
  'Adding' => 'Добавление',
  'Only for registered users' => 'Доступ только для авторизованных пользователей',
  'Title' => 'Заголовок',
  'Changing' => 'Изменение',
  'Update Time' => 'Изменено',
  'Update User' => 'Изменил',
  'Picture' => 'Изображение',
  'Search' => 'Искать',
  'Count of news on main page' => 'Количество новостей на главной',
  'Max photo height after upload' => 'Максимальная высота фото после загрузки',
  'Max thumb photo width after upload' => 'Максимальная ширина миниатюры фото',
  'Max photo width after upload' => 'Максимальная ширина фото после загрузки',
  'On Moderation' => 'На модерации',
  'News' => 'Новости',
  'News Added!' => 'Новость добавлена!',
  'News Not Found!' => 'Новость не найдена!',
  'Published' => 'Опубликовано',
  'Photo upload directory' => 'Папка загрузки фото',
  'Full Text' => 'Полная новость',
  'Fields with <span class="required">*</span> is required.' => 'Поля, отмеченные <span class="required">*</span> обязательны для заполнения.',
  'Short Text' => 'Превью',
  'Created' => 'Создано',
  'Save' => 'Сохранить',
  'Slug' => 'Ссылка',
  'Status' => 'Статус',
  'Text' => 'Текст',
  'Manage' => 'Управление',
  'Manage Site News' => 'Управление новостями сайта',
  'Photo formats' => 'Форматы фотографий',
  'Draft' => 'Черновики',
);
