<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'Slutsats',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Grattis! Serverkonfigurationen uppfyller alla krav som Yii ställer.',
  'Description' => 'Beskrivning',
  'Details' => 'Detaljer',
  'Failed' => 'Stöd saknas',
  'Memo' => 'Memo',
  'Name' => 'Namn',
  'Passed' => 'Stöds',
  'Required By' => 'Krävs för',
  'Result' => 'Resultat',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Det här skriptet kontrollerar om serverkonfigurationen uppfyller kraven för att köra <a href="http://www.yiiframework.com/">Yii</a> webbapplikationer. Det kollar att servern kör rätt version av PHP, att erforderliga  PHP-tillägg är laddade, och att inställningar i filen php.ini är korrekta.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'Tyvärr uppfyller inte serverkonfigurationen minimikraven Yii ställer.',
  'Warning' => 'Warning',
  'Yii Requirement Checker' => 'Yii - Kontroll systemkrav',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'Serverkonfigurationen uppfyller minimikraven som Yii ställer. Lägg märke till nedanstående varningar om applikationer behöver använda nämnda finesser.',
);
