<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => '',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'Parabéns! As configurações do seu servidor satisfazem todos os requisitos do Yii.',
  'Description' => 'Descrição',
  'Details' => 'Detalhes',
  'Failed' => 'Falhou',
  'Memo' => 'Detalhe',
  'Name' => 'Nome',
  'Passed' => 'OK',
  'Required By' => 'Exigido por',
  'Result' => 'Resultado',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Este script verifica se as configurações do servidor satisfazem os requisitos para executar aplicações Web que utilizem o <a href="http://www.yiiframework.com/"> Yii </a>. É verificado se o servidor está executando a versão correta do PHP, se as extensões apropriadas do PHP foram carregadas, e se as definições do arquivo php.ini estão corretas.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'Infelizmente as configurações do seu servidor não satisfazem os requisitos do Yii.',
  'Warning' => 'Advertência',
  'Yii Requirement Checker' => 'Verificador de requisitos do Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'As configurações do seu servidor satisfazem os requisitos mínimos do Yii. Por favor, preste atenção às advertências listadas abaixo caso sua aplicação for utilizar os recursos correspondentes.',
);
