<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => '检查结果',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => '恭喜！您的服务器配置完全符合Yii的要求。',
  'Description' => '检查内容',
  'Details' => '具体结果',
  'Failed' => '未通过',
  'Memo' => '备注',
  'Name' => '项目名称',
  'Passed' => '通过',
  'Required By' => '使用者',
  'Result' => '结果',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => '本网页用于确认您的服务器配置是否能满足运行<a href="http://www.yiiframework.com/">Yii</a> Web应用的要求。它将检查服务器所运行的PHP版本，查看是否安装了合适的PHP扩展模块，以及确认php.ini文件是否正确设置。',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => '您的服务器配置未能满足Yii的要求。',
  'Warning' => '警告',
  'Yii Requirement Checker' => 'Yii配置需求检查',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => '您的服务器配置符合Yii的最低要求。如果您需要使用特定的功能，请关注如下警告。',
);
