<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER缺少{vars}。',
  '$_SERVER variable' => '$_SERVER变量',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"]必须与入口文件路径一致。',
  'APC extension' => 'APC扩展模块',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => '所有和<a href="http://www.yiiframework.com/doc/api/#system.db">数据库相关的类</a>',
  'Ctype extension' => '',
  'DOM extension' => 'DOM扩展模块',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"]或$_SERVER["QUERY_STRING"]必须存在。',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => '',
  'GD installed,<br />FreeType support not installed' => '',
  'GD or ImageMagick not installed' => '',
  'Mcrypt extension' => 'Mcrypt扩展模块',
  'Memcache extension' => 'Memcache扩展模块',
  'PCRE extension' => 'PCRE扩展模块',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => '',
  'PDO MSSQL extension (pdo_dblib)' => '',
  'PDO MSSQL extension (pdo_mssql)' => '',
  'PDO MySQL extension' => 'PDO MySQL扩展模块',
  'PDO Oracle extension' => '',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL扩展模块',
  'PDO SQLite extension' => 'PDO SQLite扩展模块',
  'PDO extension' => 'PDO扩展模块',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0或更高版本是必须的。',
  'PHP version' => 'PHP版本',
  'Reflection extension' => 'Reflection扩展模块',
  'SOAP extension' => 'SOAP扩展模块',
  'SPL extension' => 'SPL扩展模块',
  'The system is unable to find the requested action "{action}".' => '',
  'This is required by encrypt and decrypt methods.' => '',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => '',
  'This is required if you are using MSSQL database from MS Windows' => '',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => '',
  'This is required if you are using MySQL database.' => '如果使用MySQL数据库，这是必须的。',
  'This is required if you are using Oracle database.' => '',
  'This is required if you are using PostgreSQL database.' => '如果使用PostgreSQL数据库，这是必须的。',
  'This is required if you are using SQLite database.' => '如果使用SQLite数据库，这是必须的。',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => '无法确定URL path info。请检查$_SERVER["PATH_INFO"]（或$_SERVER["PHP_SELF"]和$_SERVER["SCRIPT_NAME"]）的值是否正确。',
);
