<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => 'סיכום',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'ברכותיינו! סביבת השרת שלך תומכת בכל הגדרישות של Yii.',
  'Description' => 'תיאור',
  'Details' => 'פרטים',
  'Failed' => 'נכשל',
  'Memo' => 'תזכורת',
  'Name' => 'כותרת',
  'Passed' => 'עבר',
  'Required By' => 'נדרש על ידי',
  'Result' => 'תוצאה',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'הסקריפט הבא בודק אם סביבת השרת שלך תוכל לעמוד בדרישות המינימום כדי להריץ את <a href="http://www.yiiframework.com/">Yii</a> לפיתוח מערכות ווב מתקדמות. הסקריפט בודק אם השרת מריץ גרסאת PHP עדכנית, אם הרחבות מסויימת קיימות ב PHP ונטענו בהצלחה, ואם הגדרות ה php.ini מוגדרות כמו שצריך.',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => 'לצערנו סביבת השרת שלך אינה תומכת בדרישות המינימום של Yii.',
  'Warning' => 'אזהרה',
  'Yii Requirement Checker' => 'בדיקת דרישות מינימום להרצת Yii',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'הגדרות סביבת השרת שלך מתאימות לדרישות המינימום של Yii. אנא שים לב לאזהרות והערות הכתובות מטה במידה והאפליקציה שתכתוב תשתמש באחת מהאפשרויות הללו.',
);
