<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER לא מכיל {vars}.',
  '$_SERVER variable' => '$_SERVER משתנה',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] חייב להיות זהה לנתיב המלא לקובץ הראשי.',
  'APC extension' => 'תוסף APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'כל <a href="http://www.yiiframework.com/doc/api/#system.db">מחלקות מסדי הנתונים</a>',
  'Ctype extension' => '',
  'DOM extension' => 'תוסף DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"] או $_SERVER["QUERY_STRING"] חייב להיות קיים.',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => '',
  'GD installed,<br />FreeType support not installed' => '',
  'GD or ImageMagick not installed' => '',
  'Mcrypt extension' => 'תוסף Mcrypt',
  'Memcache extension' => 'תוסף Memcache',
  'PCRE extension' => 'תוסף PCRE',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => '',
  'PDO MSSQL extension (pdo_dblib)' => '',
  'PDO MSSQL extension (pdo_mssql)' => '',
  'PDO MySQL extension' => 'תוסף PDO MySQL',
  'PDO Oracle extension' => '',
  'PDO PostgreSQL extension' => 'תוסף PDO PostgreSQL',
  'PDO SQLite extension' => 'תוסף PDO SQLite',
  'PDO extension' => 'תוסף PDO',
  'PHP 5.1.0 or higher is required.' => 'PHP בגרסא 5.1.0 או יותר דרוש.',
  'PHP version' => 'גרסאת PHP',
  'Reflection extension' => 'תוסף Reflection',
  'SOAP extension' => 'תוסף SOAP',
  'SPL extension' => 'תוסף SPL',
  'This is required by encrypt and decrypt methods.' => '',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => '',
  'This is required if you are using MSSQL database from MS Windows' => '',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => '',
  'This is required if you are using MySQL database.' => 'תוסף זה נחוץ אם הינך מתכוון להשתמש במסד נתונים מסוג MYSQL.',
  'This is required if you are using Oracle database.' => '',
  'This is required if you are using PostgreSQL database.' => 'תוסף זה נחוץ אם הינך מתכוון להשתמש במסד נתונים מסוג PostgreSQL.',
  'This is required if you are using SQLite database.' => 'תוסף זה נחוץ אם הינך מתכוון להשתמש במסד נתונים מסוג SQLite.',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'לא ניתן לזהות את נתיבי הקישור. אנא וודא שהערך $_SERVER["PATH_INFO"] (או $_SERVER["PHP_SELF"] ו $_SERVER["SCRIPT_NAME"]) מכילים ערכים מתאימים.',
);
