<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Site Email' => 'Email сайта',
  'Author' => 'Автор',
  'Admin CP' => 'Админка',
  'Google Analytics Account (UA-XXXXXX-X)' => 'Аккаунт Google Analytics (UA-XXXXXX-X)',
  'Upload Directory' => 'Каталог для файлов',
  'Caching (sec.)' => 'Кэширование (сек.)',
  'Name' => 'Название',
  'Site Name' => 'Название сайта',
  'Settings' => 'Настройки',
  'Description' => 'Описание',
  'Control Panel' => 'Панель управления',
  'Go to Settings' => 'Перейти в управление',
  'Manually rename directory on FTP after save' => 'При изменении значения требуется вручную переименовать папку на FTP',
  'Manage' => 'Управление',
  'module|modules' => 'модуль|модуля|модулей',
);
