<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Author' => 'Автор',
  'Changed' => 'Изменено',
  'Created' => 'Создано',
  'Default' => 'Сбросить',
  'Error while saving!' => 'Произошла ошибка при сохранении!',
  'Key' => 'Ключ',
  'Module' => 'Модуль',
  'Module {name} haven\'t settings' => 'У модуля {name} нет настроек',
  'Save' => 'Сохранить',
  'Settings Saved!' => '',
  'Update User' => 'Изменил',
  'Value' => 'Значение',
);
