<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Conclusion' => '結果',
  'Congratulations! Your server configuration satisfies all requirements by Yii.' => 'おめでとうございます。あなたのサーバ構成はYiiの全ての要求を満しています。',
  'Description' => '説明',
  'Details' => '詳細',
  'Failed' => '不合格',
  'Memo' => '備考',
  'Name' => '名称',
  'Passed' => '合格',
  'Required By' => '必要元',
  'Result' => '結果',
  'This script checks if your server configuration meets the requirements for running <a href="http://www.yiiframework.com/">Yii</a> Web applications. It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'このスクリプトは、あなたのサーバ構成が、<a href="http://www.yiiframework.com/">Yii</a>アプリケーションを実行するための要求を満たしているかどうかを確認します。このスクリプトはサーバにおいて正しいバージョンのPHPを実行しているか、適切なPHP拡張をロードしているか、php.iniファイル設定が正しいかを確認します。',
  'Unfortunately your server configuration does not satisfy the requirements by Yii.' => '申し訳ありませんが、あなたのサーバ構成はYiiの要求を満していません。',
  'Warning' => '注意',
  'Yii Requirement Checker' => 'Yii要求チェッカ',
  'Your server configuration satisfies the minimum requirements by Yii. Please pay attention to the warnings listed below if your application will use the corresponding features.' => 'あなたのサーバ構成はYiiの最低限の要求を満しています。もしあなたのアプリケーションが対応する機能を使用している場合には以下の警告に注意してください。',
);
