<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVERは{vars}を持ちません。',
  '$_SERVER variable' => '$_SERVER変数',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"]はエントリスクリプトのパスと同じであるべきです。',
  'APC extension' => 'APC拡張',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => '全ての<a href="http://www.yiiframework.com/doc/api/#system.db">データベース関連クラス</a>',
  'Ctype extension' => '',
  'DOM extension' => 'DOM拡張',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"]か$_SERVER["QUERY_STRING"]が存在するべきです。',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => '',
  'GD installed,<br />FreeType support not installed' => '',
  'GD or ImageMagick not installed' => '',
  'Mcrypt extension' => 'Mcrypt拡張',
  'Memcache extension' => 'Memcache拡張',
  'PCRE extension' => 'PCRE拡張',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => '',
  'PDO MSSQL extension (pdo_dblib)' => '',
  'PDO MSSQL extension (pdo_mssql)' => '',
  'PDO MySQL extension' => 'PDO MySQL拡張',
  'PDO Oracle extension' => '',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL拡張',
  'PDO SQLite extension' => 'PDO SQLite拡張',
  'PDO extension' => 'PDO拡張',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0かそれ以上が必要です。',
  'PHP version' => 'PHP版数',
  'Reflection extension' => 'Reflection拡張',
  'SOAP extension' => 'SOAP拡張',
  'SPL extension' => 'SPL拡張',
  'The system is unable to find the requested action "{action}".' => '',
  'This is required by encrypt and decrypt methods.' => 'これは暗号化と複号に必要です。',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => '',
  'This is required if you are using MSSQL database from MS Windows' => '',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => '',
  'This is required if you are using MySQL database.' => 'これはMySQLデータベースをお使いなら必要です。',
  'This is required if you are using Oracle database.' => '',
  'This is required if you are using PostgreSQL database.' => 'これはPostgreSQLデータベースをお使いなら必要です。',
  'This is required if you are using SQLite database.' => 'これはSQLiteデータベースをお使いなら必要です。',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'URLパス情報を決定できません。$_SERVER["PATH_INFO"](もしくは$_SERVER["PHP_SELF"]と$_SERVER["SCRIPT_NAME"])が正しい値かどうか確認してください。',
);
