<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Catalog' => 'Каталог',
  'Create' => 'Создать',
  'Create Time' => 'Создано',
  'Create User' => 'Обновил',
  'Description' => 'META Описание',
  'File' => 'Файл',
  'Item' => 'Позиция',
  'Item Templates' => 'Параметры позиции',
  'Items' => 'Позиции',
  'Catalog of items' => 'Каталог позиций',
  'Key' => 'Ключ',
  'Keywords' => 'META Ключевые слова',
  'Manage' => 'Управление',
  'Name' => 'Название в меню',
  'Image' => 'Изображение',
  'Input type' => 'Тип поля',
  'Parent page' => 'Страница-родитель',
  'Save' => 'Сохранить',
  'Search' => 'Поиск',
  'Slug' => 'Ссылка',
  'Status' => 'Статус',
  'Text' => 'Однострочный текст',
  'Textarea' => 'Многострочный текст',
  'Title' => 'Заголовок (title)',
  'Update Time' => 'Обновлено',
  'Update User' => 'Обновил',
  'Value' => 'Значение',
);
